-- Reference SQL schema for documentation purposes.
-- Actual migrations are generated by drizzle-kit from the TypeScript schema.

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin' CHECK(role IN ('admin', 'editor', 'viewer')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE monitors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'http' CHECK(type IN ('http', 'smtp')),
  enabled INTEGER NOT NULL DEFAULT 1,
  interval_seconds INTEGER NOT NULL DEFAULT 60,
  timeout_ms INTEGER NOT NULL DEFAULT 10000,
  retry_count INTEGER NOT NULL DEFAULT 2,
  retry_delay_seconds INTEGER NOT NULL DEFAULT 5,

  -- HTTP
  url TEXT,
  method TEXT DEFAULT 'GET',
  expected_status_codes TEXT, -- JSON array

  -- SMTP
  smtp_host TEXT,
  smtp_port INTEGER,
  smtp_secure INTEGER DEFAULT 0,
  expected_banner TEXT,

  -- State
  current_status TEXT NOT NULL DEFAULT 'unknown' CHECK(current_status IN ('up', 'down', 'degraded', 'unknown')),
  last_checked_at TEXT,
  next_check_at TEXT,
  last_response_time_ms REAL,
  last_error TEXT,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,

  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE monitor_headers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  monitor_id INTEGER NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value TEXT NOT NULL
);

CREATE TABLE tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT DEFAULT '#3b82f6',
  created_at TEXT NOT NULL
);

CREATE TABLE monitor_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  monitor_id INTEGER NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE monitor_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  monitor_id INTEGER NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK(status IN ('up', 'down', 'degraded')),
  response_time_ms REAL,
  status_code INTEGER,
  error TEXT,
  checked_at TEXT NOT NULL
);

CREATE INDEX idx_monitor_results_monitor_checked ON monitor_results(monitor_id, checked_at);
CREATE INDEX idx_monitor_results_checked ON monitor_results(checked_at);

CREATE TABLE incidents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  monitor_id INTEGER NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'investigating' CHECK(status IN ('investigating', 'identified', 'monitoring', 'resolved')),
  cause TEXT,
  started_at TEXT NOT NULL,
  acknowledged_at TEXT,
  resolved_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE notification_channels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('slack', 'email')),
  enabled INTEGER NOT NULL DEFAULT 1,
  slack_webhook_url TEXT,
  email_addresses TEXT, -- JSON array
  notify_on_down INTEGER NOT NULL DEFAULT 1,
  notify_on_recovery INTEGER NOT NULL DEFAULT 1,
  cooldown_minutes INTEGER NOT NULL DEFAULT 5,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE notification_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_id INTEGER NOT NULL REFERENCES notification_channels(id) ON DELETE CASCADE,
  monitor_id INTEGER REFERENCES monitors(id) ON DELETE SET NULL,
  incident_id INTEGER REFERENCES incidents(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL CHECK(event_type IN ('down', 'recovery', 'degraded')),
  status TEXT NOT NULL CHECK(status IN ('sent', 'failed', 'skipped')),
  error TEXT,
  sent_at TEXT NOT NULL
);

CREATE INDEX idx_notification_logs_channel ON notification_logs(channel_id);
CREATE INDEX idx_notification_logs_sent ON notification_logs(sent_at);

CREATE TABLE status_pages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL DEFAULT 'Status',
  description TEXT,
  is_public INTEGER NOT NULL DEFAULT 1,
  custom_domain TEXT,
  logo_url TEXT,
  favicon_url TEXT,
  header_text TEXT,
  footer_text TEXT,
  footer_links TEXT, -- JSON
  footer_layout TEXT NOT NULL DEFAULT 'simple' CHECK(footer_layout IN ('simple', 'centered', 'columns', 'minimal')),
  theme TEXT NOT NULL DEFAULT 'minimal' CHECK(theme IN ('minimal', 'modern', 'classic', 'dark-tech')),
  color_mode TEXT NOT NULL DEFAULT 'light' CHECK(color_mode IN ('light', 'dark', 'auto')),
  font_family TEXT NOT NULL DEFAULT 'inter' CHECK(font_family IN ('inter', 'geist', 'mono-jetbrains', 'system')),
  uptime_bar_style TEXT NOT NULL DEFAULT 'pill' CHECK(uptime_bar_style IN ('pill', 'block', 'line', 'rounded')),
  custom_css TEXT,
  uptime_days_to_show INTEGER NOT NULL DEFAULT 90,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE status_page_monitors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status_page_id INTEGER NOT NULL REFERENCES status_pages(id) ON DELETE CASCADE,
  monitor_id INTEGER NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
  display_name TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  visible INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE uptime_daily_rollups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  monitor_id INTEGER NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  total_checks INTEGER NOT NULL DEFAULT 0,
  successful_checks INTEGER NOT NULL DEFAULT 0,
  failed_checks INTEGER NOT NULL DEFAULT 0,
  avg_response_time_ms REAL,
  min_response_time_ms REAL,
  max_response_time_ms REAL,
  uptime_percentage REAL NOT NULL DEFAULT 100,
  dominant_status TEXT NOT NULL DEFAULT 'unknown' CHECK(dominant_status IN ('up', 'down', 'degraded', 'unknown')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_uptime_rollups_monitor_date ON uptime_daily_rollups(monitor_id, date);
